spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: RatingDB
  application:
    name: RATING-SERVICE

server:
  port: 9999

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8444/eureka

#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: RatingDB